//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affix
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> MasterID { get; set; }
        public Nullable<System.Guid> Prev { get; set; }
        public Nullable<System.Guid> Next { get; set; }
        public string FileName { get; set; }
        public string SaveName { get; set; }
        public string FileExtension { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
        public bool IsDeleted { get; set; }
    }
}
