//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string FormType { get; set; }
        public string Template { get; set; }
        public Nullable<System.DateTime> FormedDate { get; set; }
        public string OriginHolder { get; set; }
        public string UnderTaker { get; set; }
        public string Keeper { get; set; }
        public string Amount { get; set; }
        public string UndertakenDept { get; set; }
        public string Reason { get; set; }
        public string UndertakenDeptOpinion { get; set; }
        public Nullable<System.DateTime> UndertakenDeptOpinionDate { get; set; }
        public string LeaderOpinion { get; set; }
        public Nullable<System.DateTime> LeaderOpinionDate { get; set; }
        public string KeeperOpinion { get; set; }
        public Nullable<System.DateTime> KeeperOpinionDate { get; set; }
        public string Note { get; set; }
        public string SendDept { get; set; }
        public string SendLeader { get; set; }
        public string Sender { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string Receiver { get; set; }
        public string ReceiveDept { get; set; }
        public string ReceiveLeader { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string Data { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
