//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public System.Guid ID { get; set; }
        public string MasterType { get; set; }
        public Nullable<System.Guid> MasterID { get; set; }
        public string CaseName { get; set; }
        public string CaseCode { get; set; }
        public string GoodsCode { get; set; }
        public string OriginalHolder { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Amount { get; set; }
        public string Measure { get; set; }
        public string PackageNumber { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public string WithholdMethod { get; set; }
        public string Undertaker { get; set; }
        public Nullable<System.DateTime> WithholdDate { get; set; }
        public string WithholdAddr { get; set; }
        public string KeepMethod { get; set; }
        public Nullable<System.DateTime> TurnInDate { get; set; }
        public string Receiver { get; set; }
        public string Keeper { get; set; }
        public string KeepAddr { get; set; }
        public string HandleMethod { get; set; }
        public string GoodsProperty { get; set; }
        public Nullable<System.DateTime> HandleDate { get; set; }
        public string HandleReveiver { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> Affix { get; set; }
        public bool IsDelivered { get; set; }
        public string IsFinished { get; set; }
        public bool IsEditable { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
