//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoLink
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CreateDate { get; set; }
        public Nullable<System.Guid> CreateStaff { get; set; }
        public string CaseType { get; set; }
        public Nullable<System.Guid> MasterID { get; set; }
        public Nullable<System.Guid> DetailID { get; set; }
        public Nullable<System.Guid> WithholdID { get; set; }
        public Nullable<System.Guid> KeepID { get; set; }
        public Nullable<System.Guid> TrailID { get; set; }
        public Nullable<System.Guid> IsDeleted { get; set; }
    }
}
