//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CaseID { get; set; }
        public string CaseName { get; set; }
        public string CaseCode { get; set; }
        public string PropertyCode { get; set; }
        public string OriginalHolder { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Amount { get; set; }
        public string Measure { get; set; }
        public string PackageNumber { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public string WithholdMethod { get; set; }
        public string UndertakenStaff { get; set; }
        public Nullable<System.DateTime> WithholdDate { get; set; }
        public string WithholdAddr { get; set; }
        public string KeepMethod { get; set; }
        public string TurnInDate { get; set; }
        public string ReceiveStaff { get; set; }
        public string Keeper { get; set; }
        public string KeepAddr { get; set; }
        public string Handle { get; set; }
        public string HandleDate { get; set; }
        public string HandleReceiveStaff { get; set; }
        public string Note { get; set; }
        public string Affix { get; set; }
    }
}
